theme: jekyll-theme-minimal
title: EPFL Lab in Data Science Spring 2020
repository: dslab2019/dslab2019.github.io
plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
