theme: jekyll-theme-minimal
title: EPFL Lab in Data Science Spring 2020
repository: epfl-dslab2020/epfl-dslab2020.github.io
plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
